### ISSUE TITLE
IE下 当列表增多，滚动自动出现时，会挤压内容区域

### ISSUE THREAD

**Issue by movqq** [tangdaohai/vue-happy-scroll#12]

**Comment by tangdaohai** [comment]
可以更详细的描述下问题，或者上传几张图片吗？

**Comment by movqq** [comment]
![1](https://user-images.githubusercontent.com/19924321/41706249-e4b603da-756d-11e8-828a-32bd06af5101.PNG)
![2](https://user-images.githubusercontent.com/19924321/41706259-ea559774-756d-11e8-89e6-847d1cc79fb3.PNG)
 此外当初始化有时有滚动条，IE下 点击 收缩滚动条消失时会闪一下，占用空间然后消失

**Comment by tangdaohai** [comment]
谢谢反馈。
