### ISSUE TITLE
出现Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by bibichuan** [tangdaohai/vue-happy-scroll#25]
我什么都在里面添加，只是引用了这个组件，就显示 Cannot read property '0' of undefined at o.computeStripX (happy-scroll.min.js?b355:1)这个错误。

**Comment by bibichuan** [comment]
这个问题，可能是在ele-dialog中使用造成的。

**Comment by tangdaohai** [comment]
@bibichuan 可能是渲染先后的问题，试试 `$nextTick`
