### ISSUE TITLE
子组件是v-for渲染的bug

### ISSUE THREAD

**Issue by hqzh** [tangdaohai/vue-happy-scroll#28]
Error in nextTick: "TypeError: Cannot read property '0' of undefined"

```
<happy-scroll resize>
<div>
<div v-for>
item
</div>
</div>
 </happy-scroll>
```
但是外面像这样再嵌套一层就不报了

**Comment by tangdaohai** [comment]
happy-scroll 中的组件需要保证唯一性，就像template中只能返回一个模板一样。
