### ISSUE TITLE
happy-scroll-content样式设置成 display: inline-block引发的问题

### ISSUE THREAD

**Issue by ChpShy** [tangdaohai/vue-happy-scroll#29]
在新版本中看到了这个样式以下
.happy-scroll-container .happy-scroll-content{
  /* 解决横向滚动差 20px 的问题 */
  display: inline-block;
}
设置成inline-block会导致内容没有占满全部宽度
![image](https://user-images.githubusercontent.com/25942328/50462429-3dfef280-09c0-11e9-8fd7-474e3d2c6e63.png)
正常情况下：
![image](https://user-images.githubusercontent.com/25942328/50462450-566f0d00-09c0-11e9-9d5c-0b3900e5ee6c.png)

**Comment by tangdaohai** [comment]
@ChpShy hi， 如果你不需要横向滚动的话，可以使用css强制覆盖这个属性，选一个你认为好的方式去做。
> 我会考虑应该怎么做才能更好的解决这个横向滚动的问题。
