### ISSUE TITLE
如何取消滚动条动画显示？

### ISSUE THREAD

**Issue by linboxiu** [tangdaohai/vue-happy-scroll#31]
请问，如何在鼠标移入区域显示滚动条时，不要动画？谢谢

**Comment by tangdaohai** [comment]
@linboxiu hi，只有滚动条变长或者变短的时候存在动画效果。你可以上传一个git图片吗？

**Comment by linboxiu** [comment]
![滚动条动画](https://user-images.githubusercontent.com/38677973/54064408-037ec500-424f-11e9-83d6-9bd1e06430b4.gif)

**Comment by linboxiu** [comment]
请问，鼠标移入后这种动态的显示方式能不能取消掉的呢？

**Comment by linboxiu** [comment]
@tangdaohai

**Comment by linboxiu** [comment]
我改了transition 属性，解决了，谢谢

**Comment by tangdaohai** [comment]
@linboxiu 是因为鼠标移入导致页面宽度增加了吗？才出现这个问题？

**Comment by linboxiu** [comment]
@tangdaohai 页面宽度没有增加，需求是移入马上显示滚动条，移出马上隐藏滚动条，不需要动画过度。我把你css里面的transition代码注销了。

**Comment by tangdaohai** [comment]
嗯 明白了。
