### ISSUE TITLE
鼠标滚动触发横向滚动

### ISSUE THREAD

**Issue by raind33** [tangdaohai/vue-happy-scroll#33]
现在是只有垂直方向可以用鼠标滚动滚动条，水平的不可以，虽然说也可以通过鼠标滚轮监听实现该功能，监听结束与开始事件，进行横向鼠标滚动

**Comment by tangdaohai** [comment]
@raind33 你好，谢谢你反馈问题。

关于横行滚动与竖向滚动都是用的浏览器默认设置，插件不进行干预（保持所有原生的交互行为），不提供鼠标滚轮设置滚动横竖的API。
