### ISSUE TITLE
使用 bigger-move-h="end" 当增加项的高度和超过当前高度，再增加节点会导致抖动

### ISSUE THREAD

**Issue by unbrain** [tangdaohai/vue-happy-scroll#36]

**Comment by tangdaohai** [comment]
@unbrain 可以贴一个能重现问题的项目地址吗？或者提供一个动图 展现一下问题 谢谢。

**Comment by unbrain** [comment]
- [预览](https://unbrain.github.io/scroll/dist/)  
 - [demo 代码](https://github.com/unbrain/scroll/blob/master/src/App.vue)
请您注意当前 top 达到 718 前后增加条目的区别（ 718 后开始抖动了）, 区域高设置的是 700 .您可以试一下如果是高 800 应该的 top 超过 800 就会抖动 
demo 几乎是您的源码
修改的地方就是 bigger-move-h="end"
其他就是对 li 的 fontsize 与 margin 修改过

感谢你的回复

**Comment by tangdaohai** [comment]
@unbrain 了解到了，谢谢反馈！

**Comment by tangdaohai** [comment]
sorry, 到现在才回复(很多原因...这里就不找借口了...没有将支持开源放到第一位, 罪过 罪过...)。
对于demo中到表现的现象,我已经get到了.
这里先说下为什么会有这样的表现:

> 因为新的元素是在最底部增加的,当新元素渲染完毕后($nextTick), 因为`bigger-move-h="end"`滚动条会紧接着拉到最下面, 这里scroll因为不能使用`transition`属性(scroll是js属性), 所以在表现上显的特别生硬。

当然这里可以借鉴 `jQuery animate` 中实现的效果(利用动画). 我会衡量一下利弊，可能会在 `vue-next(3.0)`中去添加这个选项。

**Comment by unbrain** [comment]
get 了  感谢😎

唐道海 <notifications@github.com> 于2019年11月25日周一 下午11:24写道：
