### ISSUE TITLE
滚动到一定距离出发事件

### ISSUE THREAD

**Issue by W-Sprites** [tangdaohai/vue-happy-scroll#37]

**Comment by tangdaohai** [comment]
@W-Sprites 可以具体描述一下问题吗？谢谢

**Comment by W-Sprites** [comment]
@tangdaohai  就是我想让滚动条离底部还有100px时触发事件 不知道怎么实现

**Comment by tangdaohai** [comment]
@W-Sprites 
1. 计算当前总高度
2. 使用`scroll-top.sync="currentTop"` 属性, watch `currentTop`
3. 在watch中计算当前top与高度的差

**Comment by W-Sprites** [comment]
@tangdaohai  好的 我试试 非常感谢
