### ISSUE TITLE
加上了resize无效

### ISSUE THREAD

**Issue by momolela** [tangdaohai/vue-happy-scroll#39]
加上了resize属性，但是浏览器窗口resize的时候，happy-scroll滚动条还存在？？？
是我配置出错了吗？
请问怎么解决？

**Comment by tangdaohai** [comment]
@momolela 你好，resize 这个属性是指监听滚动内容的大小变化，来做到滚动条的大小相应变化。并非是说浏览器窗口的resize。外层的resize影响不到。
