### ISSUE TITLE
滚动内容区域始终很小

### ISSUE THREAD

**Issue by Tanqurey** [tangdaohai/vue-happy-scroll#40]
使用时，按照说明在happy-scroll标签内外都设置了div包裹happy-scroll和滚动内容，但发现有效滚动区域始终为半个字大小。
项目结合element-ui使用，是否element-ui对该组件有影响？

**Comment by Tanqurey** [comment]
出现上述问题时，不刷新页面，修改dom结构，后台自动更新，可以正常显示
![TIM截图20190605124532](https://user-images.githubusercontent.com/44493343/58931018-894bd700-8790-11e9-87ea-693424670468.png)

但是手动刷新浏览器后，滚动区域再次萎缩。
![TIM截图20190605124532](https://user-images.githubusercontent.com/44493343/58931088-dcbe2500-8790-11e9-8b22-4cea93b7d05a.png)


注意上述所说的修改dom只是把happy-scorll标签从el-col标签内拿出去，再放回去而已。

**Comment by tangdaohai** [comment]
@Tanqurey  设置宽高20px是为了隐藏系统滚动而做的处理。

**Comment by Tanqurey** [comment]
作者您好，我是一名前端新手，那个issue的问题其实还没有找到原因，但我觉得应该还是我这边出了问题就关闭了，打扰到您真的非常抱歉。

**Comment by tangdaohai** [comment]
@Tanqurey 没关系的，有问题就要多交流，任何一个issue对开源都是有贡献意义的。
