### ISSUE TITLE
既然是滚动条插件，为何没有滚动监听呢

### ISSUE THREAD

**Issue by zhouxbalabala** [tangdaohai/vue-happy-scroll#42]

**Comment by tangdaohai** [comment]
你是想获取滚动事件的原生event属性吗？这个你可以在自己的元素上面自己监听，只要不阻止冒泡就好。
另外如果你想获取当前滚动的 `top或者left` 值可以使用 `scroll-top或者scroll-left`。

**Comment by zhouxbalabala** [comment]
但是我监听了，并没有出发事件
` let view = document.querySelector(".scroll-view");
    console.log(view);
    view.onscroll = () => {
      console.log("滚动距离" );
      var scrollTop =  view.scrollTop ;
      console.log("滚动距离" + scrollTop);
    };`
.scroll-view是我的内容区域

**Comment by tangdaohai** [comment]
@zhouxbalabala sorry，是我没说清楚，如果自己写监听应该在，可滚动的那个元素的父级上去监听`onscroll`，也就是组件内部的`.happy-scroll-container`元素。
但是我觉得你完全可以`watch` 组件的 `scroll-top` 属性

**Comment by zhouxbalabala** [comment]
嗯嗯，OK,我已经这样做了
