### ISSUE TITLE
关于vue-happy-scroll内部的东西是循环出来的问题

### ISSUE THREAD

**Issue by niangao714** [tangdaohai/vue-happy-scroll#43]
您好作者，我的vue-happy-scroll内部的东西是通过v-for循环出来的。但是在页面上面happy-scroll-container这个元素宽和高却是20px，而且控件的滚动事件也被禁用了。我查了一下，网上说循环的外面需要包裹一层盒子，我试着用一个div把循环的内容包裹起来，但是页面依然还是那样，请问我是哪个地方调用错误了吗

**Comment by tangdaohai** [comment]
@niangao714 hi，我猜你的内容是动态渲染的，所以需要`resize`这个属性。 see: https://github.com/tangdaohai/vue-happy-scroll#resize

**Comment by niangao714** [comment]
是的作者先生，我控件上也写了resize这个属性，并且右侧滚动条是出来了。但是存放内容的容器依旧计算出来的值是20px。容器内部的内容无法在页面上面显示。现在我出现的是这个问题
`<happy-scroll color="#4363C9" size="8" resize>
<div class="boxPage">
 <div v-for="(item,index) in data"  class="timing_box" :key="index">
.......
</div>
</div>
</happy-scroll>`
然后我页面上引入的只有
`import { HappyScroll } from 'vue-happy-scroll'
import 'vue-happy-scroll/docs/happy-scroll.css'`

**Comment by niangao714** [comment]
对的作者先生，我使用了您说的那个属性，并且右侧滚动条确实也出来了。并且滚动条的长度也正常，但是class="happy-scroll-container"的这个元素，自己计算出来的宽和高度是20px。让我一直无法找到问题在哪里

**Comment by tangdaohai** [comment]
@niangao714 20px是因为要隐藏浏览器的滚动条而存在的，原理上就是把系统自带的滚动条遮住。
