### ISSUE TITLE
滚动到这就不能往下滚动了   自己有了内联样式  咋改都改不了 用了important 好像只能在一处用 但是我每次的高度都不同的呀

### ISSUE THREAD

**Issue by lilingzhisunge** [tangdaohai/vue-happy-scroll#44]
![image](https://user-images.githubusercontent.com/47549443/71440769-77844e00-2739-11ea-98eb-8a7e728d0332.png)

**Comment by tangdaohai** [comment]
@lilingzhisunge 你好 可以详细的描述一下问题吗？

**Comment by lilingzhisunge** [comment]
像这个样子，真心觉得崩溃


| |
dlnu
|
|
jilinlilingzhi@163.com
|
签名由网易邮箱大师定制
在2019年12月25日 17:20，唐道海<notifications@github.com> 写道：

@lilingzhisunge 你好 可以详细的描述一下问题吗？

**Comment by tangdaohai** [comment]
> 像这个样子，真心觉得崩溃 | | dlnu | | jilinlilingzhi@163.com | 签名由网易邮箱大师定制 在2019年12月25日 17:20，唐道海<notifications@github.com> 写道： @lilingzhisunge 你好 可以详细的描述一下问题吗？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

???
