### ISSUE TITLE
异步加载数据，滚动条不显示

### ISSUE THREAD

**Issue by fupan1018** [tangdaohai/vue-happy-scroll#46]

**Comment by tangdaohai** [comment]
@fupan1018 是否使用了 `resize=true` 的配置？

**Comment by fupan1018** [comment]
谢谢您能回复，加上resize=true后，Y轴方向的滚动态还是不显示，可以通过鼠标滚动，但是不能通过滑块滚动。我做了一个测试，如果把数据写成静态的，就没有这些问题了。
视图：
![UM2K{8L{CX)))8KZIJ)W _5](https://user-images.githubusercontent.com/16321092/89142185-4eeaef00-d579-11ea-9b5c-b5bce3471ff8.png)
代码：
![L LVTEZRDQ0J_R~Q6@LZ_HG](https://user-images.githubusercontent.com/16321092/89142194-56aa9380-d579-11ea-9235-09801aac3888.png)
有什么好的办法可以解决吗？

**Comment by tangdaohai** [comment]
> 谢谢您能回复，加上resize=true后，Y轴方向的滚动态还是不显示，可以通过鼠标滚动，但是不能通过滑块滚动。我做了一个测试，如果把数据写成静态的，就没有这些问题了。
> 视图：
> ![UM2K{8L{CX)))8KZIJ)W _5](https://user-images.githubusercontent.com/16321092/89142185-4eeaef00-d579-11ea-9b5c-b5bce3471ff8.png)
> 代码：
> ![L LVTEZRDQ0J_R~Q6@LZ_HG](https://user-images.githubusercontent.com/16321092/89142194-56aa9380-d579-11ea-9235-09801aac3888.png)
> 有什么好的办法可以解决吗？

`v-for` 的那些元素用一个 div 再包裹一下即可。

```vue
<happy-scroll resize>
   <!-- 包裹一下即可 -->
   <div>
          <div v-for="...."></div>
   </div>
</happy-scroll>
```

@fupan1018

**Comment by lpGith** [comment]
我也出现了这个问题，按你说的加了还是没有滚动条，但是可以滚动

**Comment by lpGith** [comment]
我也出现了这个问题，按你说的加了还是没有滚动条，但是可以滚动

**Comment by tangdaohai** [comment]
> 我也出现了这个问题，按你说的加了还是没有滚动条，但是可以滚动

方便给一下 demo 或者贴一下代码吗？

**Comment by lpGith** [comment]
通过接口获取的数据展示，滚动条就不显示，静态的数据就可以正常显示了
<happy-scroll color="rgba(155,178,250,1)" size="10" hide-horizontal resize style="height: 280px;">
                                    <a-timeline class="steps" pendingDot="1">
                                        <div>
                                            <a-timeline-item v-for="(item,index) in TalkSummary" :key="index">
                                                <div>
                                                    {{item.time}}
                                                    <span class="time">
                                                <div class="gj-record">
                                                    <span style="margin:12px 8px 12px 16px;vertical-align: top">跟进记录</span>
                                                    <span style="display: inline-block;width: 187px">{{item.record}}</span>
                                                </div>
                                                <div class="gj-man">
                                                    <span style="margin-left: 16px;margin-top: 12px;margin-right: 20px">跟进人</span>
                                                    <span>{{item.name}}</span>
                                                </div>
                                            </span>
                                                </div>
                                            </a-timeline-item>
                                        </div>
                                        <a-timeline-item color="white">
                                        </a-timeline-item>
                                    </a-timeline>
                        </happy-scroll>

**Comment by lpGith** [comment]
``<happy-scroll color="rgba(155,178,250,1)" size="10" hide-horizontal resize style="height: 280px;">
                                    <a-timeline class="steps" pendingDot="1">
                                        <div>
                                            <a-timeline-item v-for="(item,index) in TalkSummary" :key="index">
                                                <div>
                                                    {{item.time}}
                                                    <span class="time">
                                                <div class="gj-record">
                                                    <span style="margin:12px 8px 12px 16px;vertical-align: top">跟进记录</span>
                                                    <span style="display: inline-block;width: 187px">{{item.record}}</span>
                                                </div>
                                                <div class="gj-man">
                                                    <span style="margin-left: 16px;margin-top: 12px;margin-right: 20px">跟进人</span>
                                                    <span>{{item.name}}</span>
                                                </div>
                                            </span>
                                                </div>
                                            </a-timeline-item>
                                        </div>
                                        <a-timeline-item color="white">
                                        </a-timeline-item>
                                    </a-timeline>
                        </happy-scroll>

**Comment by lpGith** [comment]
![image](https://user-images.githubusercontent.com/44292925/91389172-5eedaa00-e86b-11ea-8e4e-26a885fa865d.png)

**Comment by tangdaohai** [comment]
@lpGith `<a-timeline>` 这个组件都有什么 css 属性？

**Comment by lpGith** [comment]
> @lpGith `<a-timeline>` 这个组件都有什么 css 属性？
这个是ant-design-vue 里面的时间轴组件，现在的情况是我把浏览器缩小就有显示，是不是和里面的元素的大小有关系呢？之前不显示的我设置元素的宽高是固定像素的，现在设置的是百分比

**Comment by tangdaohai** [comment]
@lpGith 做了个 demo 表现正常，访问一下 点击 `加1条` 查看一下：

https://codesandbox.io/s/elastic-ramanujan-jwn70?file=/src/App.vue
