### ISSUE TITLE
如何获取滚动条的translate值，即他y轴滚动条滑动的距离

### ISSUE THREAD

**Issue by zzzyuan0** [tangdaohai/vue-happy-scroll#48]

**Comment by tangdaohai** [comment]
@1537069101 y 轴滚动条距离顶部的距离？ -> https://github.com/tangdaohai/vue-happy-scroll#scroll-top

**Comment by zzzyuan0** [comment]
> @1537069101 y 轴滚动条距离顶部的距离？ -> https://github.com/tangdaohai/vue-happy-scroll#scroll-top

我获取这个值，他一直都是为0，其实我只想监听滚动条滚动时，他距离最上面的距离有多远，其实 v-on:scroll.passive="handleScroll"这个功能可以满足我的要求，但是他没有任何效果

**Comment by zzzyuan0** [comment]
> @1537069101 y 轴滚动条距离顶部的距离？ -> https://github.com/tangdaohai/vue-happy-scroll#scroll-top

我现在已经好了需要加一条这个
mounted:function() {
            window.addEventListener('scroll', this.handleScroll,true)
        },

**Comment by tangdaohai** [comment]
@1537069101 如图，`当前 TOP ` 是你的需求吧？可以查看此 [demo](https://tangdaohai.github.io/vue-happy-scroll/)
![image](https://user-images.githubusercontent.com/10151071/100423911-c95ef200-30c7-11eb-8011-1883ae075819.png)

**Comment by zzzyuan0** [comment]
我很好奇，我通过按钮能控制滚轮移动，并且输出相对应的scrollTop他是有数据的，但是我通过监听滚轮的滑动，实事输出scrollTop他的数据永远是0，其实我需要的功能是，当我将滚轮滑动100px左右时，我需要让某一个div隐藏，但是现在我的问题是，我无法获取到滚动滑动的数据，因此我只能当滚动一有滑动就隐藏我的div，如果你能告知我正确的解决方法，我将十分感谢
<happy-scroll :scroll-top="scrollTop" @vertical-start="handleScroll"  v-on:scroll.passive="scrollClose"  ref="happyScroll" resize&gt;
scrollClose(){
    console.log(this.scrollTop) // 数据永远是0
  this.isShow = true;
},
scrollMove(){
    console.log(this.scrollTop) // 此时的输出是有数据的
  this.scrollTop += 10
},
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tangdaohai/vue-happy-scroll"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 下午3:48
收件人:&nbsp;"tangdaohai/vue-happy-scroll"<vue-happy-scroll@noreply.github.com&gt;;
抄送:&nbsp;"杂货猿"<1537069101@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tangdaohai/vue-happy-scroll] 如何获取滚动条的translate值，即他y轴滚动条滑动的距离 (#48)





 
@1537069101 如图，当前 TOP  是你的需求吧？可以查看此 demo

**Comment by tangdaohai** [comment]
@1537069101 使用方式的问题：<happy-scroll :scroll-top="scrollTop" ==> <happy-scroll :scroll-top`.sync`="scrollTop" 需要增加 sync 修饰符，获取同步 scrollTop 的 value。

**Comment by zzzyuan0** [comment]
十分感谢，你的方法是成功的------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;唐道海&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月27日(星期五) 晚上11:00
收件人:&nbsp;&quot;tangdaohai/vue-happy-scroll&quot;<vue-happy-scroll@noreply.github.com&gt;;
抄送:&nbsp;&quot;zzzyuan&quot;<1537069101@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tangdaohai/vue-happy-scroll] 如何获取滚动条的translate值，即他y轴滚动条滑动的距离 (#48)
