### ISSUE TITLE
动态绑定的数据会导致滚动条会无法滚动到最低端，无法触发滚动条触底事件

### ISSUE THREAD

**Issue by xiaoqizhu** [tangdaohai/vue-happy-scroll#51]
在设置每一条数据的高度固定并且容器高度固定的情况下，动态绑定的数据会导致滚动条会无法滚动到最低端，如果使用静态的数据渲染，滚动条正常触底

**Comment by xiaoqizhu** [comment]
在经过长时间的尝试后，发现，容器内的元素如果设置了边框，padding,margin,就会导致这个问题，去掉所有边框，padding,margin后，滚动条正常触底，但是页面底部会被挡住一部分，需要给容器设置padding-bottom:20px;即可解决

**Comment by xiaoqizhu** [comment]
能不能把setContainerSize 方法里的+20px给去掉，就是这个影响的

**Comment by xiaoqizhu** [comment]
新问题，连续触发八次触底事件后，无法触底了，需要手动拉一下，我受够了，决定单纯使用该插件展示滚动条，loadmore功能使用Intersection Observer方法实现

**Comment by tangdaohai** [comment]
> 在经过长时间的尝试后，发现，容器内的元素如果设置了边框，padding,margin,就会导致这个问题，去掉所有边框，padding,margin后，滚动条正常触底，但是页面底部会被挡住一部分，需要给容器设置padding-bottom:20px;即可解决

这个的原因应该是内部元素有 margin 或者 padding 时,外部元素没有获取到正确的高度，可以尝试增加 `overflow: hidden`。

另外选择合适的工具库是正确的，祝编码愉快~
