### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by yanaxua** [tangdaohai/vue-happy-scroll#6]
1-可否有一个监测外部窗口resize事件的接口,或者一个参数能从外部触发,

2-与elementUI中tabTabs 标签页这样的插件配合使用,每个tab内容中都会有子滚动区域,只有第一个显示的才会有正确的宽高计算,因为happy-scroll如果内容不变,只在mounted计算一次,导致后面的视图宽高为0,这个问题我加了一个v-if可以解决,

3-插件有兼容问题吗?我写的案例在火狐下的高度计算container层和content层高度全为内容的高度,导致无法滚动,谷歌正常.

**Comment by yanaxua** [comment]
查看了一下,确实是兼容的问题,包括横向滚动条,在火狐下也是显示bug,同时出现了原生滚动条和组件滚动条,火狐版本(59.0.1 (64 位))

**Comment by tangdaohai** [comment]
@yanaxua 谢谢你的建议。年前一直计划升级迭代的事情，年后还在推进，只不过进度稍慢。

1. 在新版本中会计划开放父级 resize 方法接口
2. 兼容性：可以跟随 vue 的版本来确定兼容性
3. 欢迎代码参与进行 PR 😆
